## Intro

Welcome to Chic-fil-a Database! This is a project with the goal to find the most price effective use of points on the Chic-Fil-A one app. The worksheet was written in Python as a Jupyter Notebook, running queries from an SQL database with the SQLite database engine.

## Schema

Rewards (
<br>
    &emsp;"Name" TEXT
    <br>
    &emsp;"Meal" TEXT
    <br>
    &emsp;"Points" INTEGER
    <br>
    &emsp;"Reward Rank" TEXT
    <br>
    &emsp;"Price" REAL
    <br>
    &emsp;"Price per Point" REAL
    <br>
)
<br>

Import sqlite3 for use of the database, and connect to the database with the Chic-Fil-A One information

In [1]:
# Setup sqlite3 and pandas
import sqlite3
import pandas as pd

In [2]:
# Connect to ChicFilA Database
db = sqlite3.connect('ChicFilA.db')
cursor = db.cursor()

## Scenario 1

Let's find the information we came for! What are the top five menu items with the best value?

In [3]:
sql1 = """
SELECT * FROM Rewards R
ORDER BY "Price per Point" DESC
LIMIT 5
"""
cursor.execute(sql1)
df = pd.DataFrame()
for r in cursor:
    d = {
        "Name": r[0],
        "Meal": r[1],
        "Points": r[2],
        "Reward Rank": r[3],
        "Price": r[4],
        "Price Per Point": r[5]
    }
    df = df.append(pd.Series(d), ignore_index=True)
display(df)

,Meal,Name,Points,Price,Price Per Point,Reward Rank
0,Side,Kale Crunch Side,400.0,4.85,1.21,Basic
1,Treat,Icedream Cone,200.0,2.19,1.10,Basic
2,Side,Small Waffle Potato Fries,300.0,2.79,0.93,Basic
3,Treat,Chocolate Fudge Brownie,300.0,2.65,0.88,Basic
4,Entrée,30 ct Nuggets,2500.0,21.69,0.87,Signature Member Reward

## Scenario 2

Let's say we only have 500 points. What are the best value items under 500 points?

In [4]:
sql2 = """
SELECT * FROM Rewards R
WHERE "Points" < 500
ORDER BY "Price per Point" DESC
LIMIT 3
"""
cursor.execute(sql2)
df = pd.DataFrame()
for r in cursor:
    d = {
        "Name": r[0],
        "Meal": r[1],
        "Points": r[2],
        "Reward Rank": r[3],
        "Price": r[4],
        "Price Per Point": r[5]
    }
    df = df.append(pd.Series(d), ignore_index=True)
display(df)

,Meal,Name,Points,Price,Price Per Point,Reward Rank
0,Side,Kale Crunch Side,400.0,4.85,1.21,Basic
1,Treat,Icedream Cone,200.0,2.19,1.10,Basic
2,Side,Small Waffle Potato Fries,300.0,2.79,0.93,Basic

## Scenario 3

I am going for breakfast and want to spend my points wisely. Which items should I avoid?

In [5]:
sql3 = """
SELECT * FROM Rewards R
WHERE "Meal" = "Breakfast"
ORDER BY "Price per Point" ASC
LIMIT 3
"""
cursor.execute(sql3)
df = pd.DataFrame()
for r in cursor:
    d = {
        "Name": r[0],
        "Meal": r[1],
        "Points": r[2],
        "Reward Rank": r[3],
        "Price": r[4],
        "Price Per Point": r[5]
    }
    df = df.append(pd.Series(d), ignore_index=True)
display(df)

,Meal,Name,Points,Price,Price Per Point,Reward Rank
0,Breakfast,Chicken Breakfast Sandwich,700.0,4.45,0.64,Basic
1,Breakfast,Hash Browns Side,300.0,1.99,0.66,Basic
2,Breakfast,Egg White Grill,900.0,5.99,0.67,Basic

## Scenario 4

I'm really craving a sandwich. Which kinds have the best point value?

In [6]:
sql4 = """
SELECT * FROM Rewards R
WHERE "Name" LIKE "%sandwich%"
ORDER BY "Price per Point" DESC
LIMIT 3
"""
cursor.execute(sql4)
df = pd.DataFrame()
for r in cursor:
    d = {
        "Name": r[0],
        "Meal": r[1],
        "Points": r[2],
        "Reward Rank": r[3],
        "Price": r[4],
        "Price Per Point": r[5]
    }
    df = df.append(pd.Series(d), ignore_index=True)
display(df)

     Meal                    Name  Points  Price  Price Per Point Reward Rank
0  Entrée  Spicy Chicken Sandwich   800.0   6.45             0.81       Basic
1  Entrée        Chicken Sandwich   800.0   6.15             0.77       Basic
2  Entrée   Spicy Deluxe Sandwich  1000.0   7.25             0.73       Basic

## Reference

Below is shown the full output of the database table for reference

In [7]:
sql5 = """
SELECT * FROM Rewards R
ORDER BY "Price" ASC
"""
cursor.execute(sql5)
df = pd.DataFrame()
for r in cursor:
    d = {
        "Name": r[0],
        "Meal": r[1],
        "Points": r[2],
        "Reward Rank": r[3],
        "Price": r[4],
        "Price Per Point": r[5]
    }
    df = df.append(pd.Series(d), ignore_index=True)
display(df)

,Meal,Name,Points,Price,Price Per Point,Reward Rank
0,Treat,Chocolate Chunk Cookie,300.0,1.99,0.66,Basic
1,Breakfast,Hash Browns Side,300.0,1.99,0.66,Basic
2,Treat,Icedream Cone,200.0,2.19,1.10,Basic
3,Beverage,Coffee,400.0,2.55,0.64,Basic
4,Treat,Chocolate Fudge Brownie,300.0,2.65,0.88,Basic
5,Side,Small Waffle Potato Fries,300.0,2.79,0.93,Basic
6,Beverage,Freshly-Brewed Iced Tea,400.0,2.79,0.70,Basic
7,Beverage,Soft Drink,400.0,2.79,0.70,Basic
8,Side,Waffle Potato Chips,400.0,2.85,0.71,Basic
9,Beverage,Sunjoy,600.0,3.19,0.53,Basic
10,Beverage,Lemonade,600.0,3.19,0.53,Basic
11,8 oz Sauces,8 oz Sauce,600.0,3.25,0.54,Red Member Reward
12,Side,Medium Waffle Potato Fries,400.0,3.29,0.82,Basic
13,Side,Large Waffle Potato Fries,500.0,3.69,0.74,Basic
14,Entrée,5 ct Nuggets,600.0,3.95,0.66,Basic
15,Entrée,2 ct Chick-n-Strips,600.0,4.39,0.73,Basic
16,Breakfast,Chicken Breakfast Sandwich,700.0,4.45,0.64,Basic
17,Entrée,5 ct Grilled Nuggets,800.0,4.45,0.56,Basic
18,Beverage,Iced Coffee,600.0,4.55,0.76,Basic
19,Side,Cup of Soup,800.0,4.65,0.58,Basic
20,Side,Kale Crunch Side,400.0,4.85,1.21,Basic
21,Side,Medium Fruit Cup,800.0,4.85,0.61,Basic
22,Side,Medium Mac & Cheese,800.0,4.85,0.61,Basic
23,Side,Side Salad,800.0,4.85,0.61,Basic
24,Breakfast,Sausage/Bacon Breakfast Sandwich,700.0,4.99,0.71,Basic
25,Treat,Frosted Beverages and Floats,800.0,5.25,0.66,Basic
26,Treat,Milkshake,800.0,5.35,0.67,Basic
27,Side,Berry Parfait,800.0,5.45,0.68,Basic
28,Breakfast,4 ct Chick-n-Minis,700.0,5.69,0.81,Basic
29,Entrée,Kid's Meal,1200.0,5.95,0.50,Red Member Reward
30,Breakfast,Egg White Grill,900.0,5.99,0.67,Basic
31,Breakfast,Hash Brown Scramble Burrito,900.0,5.99,0.67,Basic
32,Breakfast,Hash Brown Scramble Bowl,900.0,5.99,0.67,Basic
33,Entrée,Chicken Sandwich,800.0,6.15,0.77,Basic
34,Entrée,8 ct Nuggets,900.0,6.25,0.69,Basic
35,Entrée,Spicy Chicken Sandwich,800.0,6.45,0.81,Basic
36,Entrée,3 ct Chick-n-Strips,900.0,6.55,0.73,Basic
37,Entrée,Deluxe Sandwich,1000.0,6.95,0.70,Basic
38,Beverage,Gallon Freshly-Brewed Iced Tea,1500.0,7.00,0.47,Red Member Reward
39,Entrée,8 ct Grilled Nuggets,1000.0,7.09,0.71,Basic
40,Side,Bowl of Soup,1200.0,7.09,0.59,Basic
41,Entrée,Spicy Deluxe Sandwich,1000.0,7.25,0.73,Basic
42,Entrée,Grilled Chicken Sandwich,1200.0,7.55,0.63,Basic
43,Entrée,4 ct Chick-n-Strips,1200.0,8.19,0.68,Basic
44,Entrée,12 ct Nuggets,1200.0,8.69,0.72,Basic
45,Entrée,Cool Wrap,1500.0,9.59,0.64,Basic
46,Entrée,Grilled Chicken Club Sandwich,1500.0,9.85,0.66,Basic
47,Entrée,12 ct Grilled Nuggets,1500.0,10.09,0.67,Basic
48,Entrée,Salad,2000.0,10.69,0.53,Basic
49,Meals,Meal,2500.0,10.99,0.44,Basic
50,Beverage,Gallon Sunjoy,3000.0,11.00,0.37,Signature Member Reward
51,Treat,6 ct Cookie,1500.0,11.39,0.76,Red Member Reward
52,Beverage,Gallon Lemonade,3000.0,12.75,0.43,Signature Member Reward
53,Breakfast,10 ct Chick-n-Minis,1700.0,14.19,0.83,Red Member Reward
54,Entrée,30 ct Nuggets,2500.0,21.69,0.87,Signature Member Reward